version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - '3308:3308'
    environment:
       MYSQL_DATABASE: 'django'
       MYSQL_USER: 'django'
       MYSQL_PASSWORD: 'django'
       MYSQL_ROOT_PASSWORD: '22082003'
    volumes:
      - .setup.sql:/docker-entrypoint-initbd.d/setup.sql

  web:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 -w 4 django_project.wsgi"
    volumes:
      - .:/django_project
      - staticfiles:/django_project/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  staticfiles: