# Generated by Django 3.1.1 on 2022-08-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menuitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
    ]
